export const gitignore = `
.tmp
.DS_Store
node_modules
build

# Log files
npm-debug.log*
yarn-debug.log*
yarn-error.log*
yarn.lock

# Editor directories and files
.idea
# .vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# generated by wii
index.html

# local env
.env.local

.vscode
*.local.*

`;

export const vscodeConfig = `
{
    "cSpell.words": [
        "evanzyli",
        "lizhiyu",
        "vite"
    ]
}
`;

export const dockerFile = `
FROM nginx
COPY . /app
WORKDIR /app
ENV TZ="Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN npm config set registry http://registry.npm.taobao.org
RUN npm install
EXPOSE 3000
CMD ["npm", "run" , "dev"]
`;

export const jenkinsfile = `

pipeline {
    agent any
}
`;

export const commitLint = `
module.exports = {
    extends: ['@commitlint/config-conventional'],
  }  
`;